language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdbi0-dev pkg-config
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules
  - make
  - make check
compiler:
  - gcc
  - clang
